version: '3'
services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mqtt/passwd:/mosquitto/config/passwd
      - ./mqtt//data:/mosquitto/data
      - ./mqtt//log:/mosquitto/log
    restart: always
  telegraf:
    container_name: telegraf
    image: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
      - influxdb
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
    restart: always
    container_name: telegraf
  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=telegraf
    volumes:
      - ./influxdb:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    ports:
      - "8086:8086"
    restart: always
  chronograf:
    container_name: chronograf
    image: chronograf
    volumes:
      - /var/lib/chronograf:/var/lib/chronograf
    ports:
      - "8888:8888"
    restart: always
    links:
      - influxdb


